
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtGui import QIcon
import sys


class Interface(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 624)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setToolTipDuration(0)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setWindowTitle("PLc_App")
        MainWindow.setWindowIcon(QIcon("Icons/plc.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(250, 10, 771, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 30, 641, 461))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 391, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setTabletTracking(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(40, 70, 621, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 160, 800))
        self.widget.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_history = QtWidgets.QWidget(self.widget)
        self.widget_history.setObjectName("widget_history")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_history)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_history = QtWidgets.QPushButton(self.widget_history)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_history.setFont(font)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Icons/moins.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_history.setIcon(icon)
        self.btn_history.setCheckable(True)
        self.btn_history.setObjectName("btn_history")
        self.verticalLayout_4.addWidget(self.btn_history)
        self.gridLayout.addWidget(self.widget_history, 4, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget_8, 5, 0, 1, 1)
        self.widget_tag = QtWidgets.QWidget(self.widget)
        self.widget_tag.setObjectName("widget_tag")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_tag)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_tag = QtWidgets.QPushButton(self.widget_tag)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tag.setFont(font)

        self.btn_tag.setIcon(icon)
        self.btn_tag.setCheckable(True)
        self.btn_tag.setObjectName("btn_tag")
        self.verticalLayout_5.addWidget(self.btn_tag)
        self.gridLayout.addWidget(self.widget_tag, 2, 0, 1, 1)

        self.menu_tag = QtWidgets.QWidget(self.widget)
        self.menu_tag.setObjectName("menu_tag")
        self.menu_tag.setVisible(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_tag)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_add_tag = QtWidgets.QPushButton(self.menu_tag)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.btn_add_tag.setFont(font)
        self.btn_add_tag.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.btn_add_tag.setAutoRepeatDelay(300)
        self.btn_add_tag.setFlat(False)
        self.btn_add_tag.setObjectName("btn_add_tag")
        self.verticalLayout_2.addWidget(self.btn_add_tag)
        self.btn_delete_tag = QtWidgets.QPushButton(self.menu_tag)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.btn_delete_tag.setFont(font)
        self.btn_delete_tag.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.btn_delete_tag.setAutoRepeatDelay(300)
        self.btn_delete_tag.setFlat(False)
        self.btn_delete_tag.setObjectName("btn_delete_tag")
        self.verticalLayout_2.addWidget(self.btn_delete_tag)
        self.gridLayout.addWidget(self.menu_tag, 3, 0, 1, 1)
        self.widget_plc = QtWidgets.QWidget(self.widget)
        self.widget_plc.setObjectName("widget_plc")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_plc)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plc = QtWidgets.QPushButton(self.widget_plc)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plc.setFont(font)

        self.plc.setIcon(icon)
        self.plc.setCheckable(True)
        self.plc.setObjectName("plc")
        self.verticalLayout_6.addWidget(self.plc)
        self.gridLayout.addWidget(self.widget_plc, 0, 0, 1, 1)
        self.menu_plc = QtWidgets.QWidget(self.widget)
        self.menu_plc.setObjectName("menu_plc")
        self.menu_plc.setVisible(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_plc)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_plc = QtWidgets.QPushButton(self.menu_plc)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_plc.setFont(font)
        self.btn_plc.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.btn_plc.setAutoRepeatDelay(300)
        self.btn_plc.setFlat(False)
        self.btn_plc.setObjectName("btn_plc")
        self.verticalLayout.addWidget(self.btn_plc)
        self.btn_modify = QtWidgets.QPushButton(self.menu_plc)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_modify.setFont(font)
        self.btn_modify.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.btn_modify.setAutoRepeatDelay(300)
        self.btn_modify.setFlat(False)
        self.btn_modify.setObjectName("btn_modify")
        self.verticalLayout.addWidget(self.btn_modify)
        self.btn_update = QtWidgets.QPushButton(self.menu_plc)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_update.setFont(font)
        self.btn_update.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.btn_update.setAutoRepeatDelay(300)
        self.btn_update.setFlat(False)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout.addWidget(self.btn_update)
        self.gridLayout.addWidget(self.menu_plc, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuview = QtWidgets.QMenu(self.menubar)
        self.menuview.setObjectName("menuview")
        self.menuSocial = QtWidgets.QMenu(self.menubar)
        self.menuSocial.setObjectName("menuSocial")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionf1 = QtWidgets.QAction(MainWindow)
        self.actionf1.setChecked(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/deconnectez.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionf1.setIcon(icon1)
        self.actionf1.setObjectName("actionf1")
        self.actionview_V = QtWidgets.QAction(MainWindow)
        self.actionview_V.setObjectName("actionview_V")
        self.actiontype_T = QtWidgets.QAction(MainWindow)
        self.actiontype_T.setObjectName("actiontype_T")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/sign-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew.setIcon(icon2)
        self.actionnew.setObjectName("actionnew")
        self.menuFile.addAction(self.actionf1)
        self.menuFile.addAction(self.actionnew)
        self.menuview.addAction(self.actionview_V)
        self.menuSocial.addAction(self.actiontype_T)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuview.menuAction())
        self.menubar.addAction(self.menuSocial.menuAction())
        self.toolBar_2.addAction(self.actionnew)
        self.toolBar_2.addAction(self.actionf1)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.plc.toggled['bool'].connect(self.menu_plc.setVisible) # type: ignore
        self.btn_tag.toggled['bool'].connect(self.menu_tag.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_plc.clicked.connect(lambda : self.stackedWidget.setCurrentWidget(self.page_1))
        self.btn_modify.clicked.connect(lambda : self.stackedWidget.setCurrentWidget(self.page_2))
        self.btn_update.clicked.connect(lambda : self.stackedWidget.setCurrentWidget(self.page_3))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PLC"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N°"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BACK"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SOLT"))
        self.pushButton_3.setText(_translate("MainWindow", "Modify"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N°"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", " BACK"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SLOT"))
        self.btn_history.setText(_translate("MainWindow", "History"))
        self.btn_tag.setText(_translate("MainWindow", "Tag"))
        self.btn_add_tag.setText(_translate("MainWindow", "Add Tag"))
        self.btn_delete_tag.setText(_translate("MainWindow", "Delete Tag"))
        self.plc.setText(_translate("MainWindow", "PLC"))
        self.btn_plc.setText(_translate("MainWindow", "Connect PLC"))
        self.btn_modify.setText(_translate("MainWindow", "Modify PLC"))
        self.btn_update.setText(_translate("MainWindow", "Update PLC"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuview.setTitle(_translate("MainWindow", "view"))
        self.menuSocial.setTitle(_translate("MainWindow", "Type"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionf1.setText(_translate("MainWindow", "Exit(X)"))
        self.actionview_V.setText(_translate("MainWindow", "view(V)"))
        self.actiontype_T.setText(_translate("MainWindow", "type(T)"))
        self.actionnew.setText(_translate("MainWindow", "new"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Interface()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
