# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import snap7
from PyQt5.QtWidgets import QApplication, QTableWidget, QWidget, QTableWidgetItem
import sys

from snap7.util import get_int

from Model.Tag import tag

class history(QWidget):
    tag_obj = None
    def __init__(self):
        super().__init__()

        self.resize(800,500)
        self.tab_history = QTableWidget(self)
        self.tab_history.resize(800,400)
        self.tab_history.move(0, 10)
        self.tag_obj= tag()
        self.tab_history.setColumnCount(len(self.tag_obj.list_of_tags())+2) # 2 = 1+1 (field time & id_plc)
        header = []
        header = self.tag_obj.list_names_of_tags()
        header.append("time")
        header.append("plc")

        self.tab_history.setHorizontalHeaderLabels(header)

        self.display_history()


    def display_history(self): # Not Complete
        list_result=self.tag_obj.get_all_tags_and_time() # list object of tags
        # id_op = row[0]
        # name_tag = row[1]
        # data_type = row[2]
        # value row[4]
        # time row [5]
        # N plc [6]

        size_list_value_time_tag=len(list_result)
        id_total_result=0

        print("Size OperationAfter devision: ",int(size_list_value_time_tag / len(self.tag_obj.list_of_tags())))

        #for row_nbr in range (0,int(size_list_value_time_tag / len(self.tag_obj.list_of_tags()))):
        for row_nbr in range(0, 3):
            print("Row nbr :",row_nbr," ID_res_total:",id_total_result,"Number of tags:",len(self.tag_obj.list_of_tags()))

            self.tab_history.insertRow(row_nbr)
            number_tag = len(self.tag_obj.list_of_tags())
            i=0
            while i<number_tag:
                print(" Iteration:",i)
                line_res=list_result[id_total_result]
                id_op = line_res[0]
                name_tag = line_res[1]
                data_type = line_res[2]
                value = 0
                if data_type == "int":
                    value = get_int(line_res[4], 0)
                elif data_type == "real":
                    value = snap7.util.get_real(line_res[4], 0)
                elif data_type == "bool":
                    ad_bit = line_res[3]
                    value = snap7.util.get_bool(line_res[4], 0, ad_bit)

                print("ID_op:", id_op, " Name:", name_tag, "data_type:", data_type, " value:", value)

                self.tab_history.setItem(row_nbr,i,QTableWidgetItem(str(value)))
                id_total_result += 1
                i+=1


        def display_history_opti():
            print("")

# app=QApplication(sys.argv)
# hist_frm=history()
# hist_frm.show()
# app.exec_()







# if __name__ == "__main__":
#     import sys
#     app = QApplication(sys.argv)
#     Form = QWidget()
#
#     Form.show()
#     sys.exit(app.exec_())
